version: '3'

services:
  app:
    build: .
    command: ash -c "rm -f tmp/pids/server.pid && ./bin/rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=example
      - EDITOR=vi
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp:cached

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
